# Generated by Django 4.1.1 on 2022-11-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searchapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='제목')),
                ('link', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('subtitle', models.TextField(null=True)),
                ('pub_date', models.TextField(null=True)),
                ('director', models.TextField(null=True)),
                ('actor', models.TextField(null=True)),
                ('user_rating', models.TextField(null=True)),
            ],
            options={
                'db_table': 'searchmovie',
            },
        ),
    ]
