# Generated by Django 4.1.1 on 2022-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searchapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('link', models.TextField(blank=True, db_column='Link', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('subtitle', models.TextField(blank=True, db_column='Subtitle', null=True)),
                ('pub_date', models.TextField(blank=True, db_column='Publication Date', null=True)),
                ('director', models.TextField(blank=True, db_column='Director', null=True)),
                ('actor', models.TextField(blank=True, db_column='Actor', null=True)),
                ('user_rating', models.TextField(blank=True, db_column='User Rating', null=True)),
            ],
            options={
                'db_table': 'search_movie',
            },
        ),
    ]
