# Generated by Django 4.1.1 on 2022-10-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchapi',
            table='searchapi',
        ),
    ]
