# Generated by Django 4.1.1 on 2022-10-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0002_alter_searchapi_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchapi',
            table='searchmovie',
        ),
    ]
