# Generated by Django 4.1.1 on 2023-01-19 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("url", models.TextField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="genre_recommand4",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("url", models.TextField(default="0")),
                ("movie_id", models.IntegerField()),
                ("genre_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("poster_path", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Usergenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.genre"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("popularity", models.FloatField()),
                ("vote_average", models.FloatField()),
                ("overview", models.TextField()),
                ("poster_path", models.CharField(max_length=200)),
                ("genre_ids", models.ManyToManyField(to="movie.genre")),
            ],
        ),
    ]
