# Generated by Django 4.1.3 on 2023-03-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_staytime"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaverLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
